title:              Muay Thai
email:              v-networks@posteo.de
description:        Meditationen
author:             V
baseurl:            "/mt_meditations/"
url:                "https://v-glb.github.io"

# Social Profiles
github_username:    v-glb
xing_username: Vadim_Glebow

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
